services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres-main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_chat
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_volume_data:/db
    depends_on:
      - redis

volumes:
  redis_volume_data:
  redis_insight_volume_data: